### ISSUE TITLE
Alpha Release Roadmap

### ISSUE THREAD

**Issue by Zolkin1** [Caltech-AMBER/obelisk#119]
Critical Path:
- [ ] Remove requirement for obelisk messages
- [ ] Remove config strings, add yaml parsing support
- [ ] Build system fixes
- [ ] Docs
- [ ] Tests
- [ ] Rosdep support

Additional Features:
- [ ] Simulation based timing
- [ ] Full stack pausing
- [ ] Not enforcing full robot stack in the yaml (e.g. run the stack with only the estimator)
- [ ] Shorten `obk` commands
- [ ] Go back through the issues
- [ ] C++ mujoco support only

Robot Specific:
- [ ] C++ code only for hardware unless required otherwise
- [ ] Unitree interfaces (Go2, G1)
- [ ] Fr3

Sensors:
- [ ] Zed node & Zed and dependencies
- [ ] Realsense
