### ISSUE TITLE
Post-Alpha Todo Items

### ISSUE THREAD

**Issue by Zolkin1** [Caltech-AMBER/obelisk#123]
- [ ] Remove `ObeliskNode` subclasses
- [ ] consider trying to strongly encourage or enforce "wide" subscribers that can accept many message types for generic tool implementations (how do we do this cleanly for cpp?)
- [ ] figure out a better way to do the component keys
